- .github/workflows/flownet.yml
- README.md
- setup.py
This finishes the `flownet` part of PyPI deploy.
> Deploy to PyPI on releases

- build_environment.sh
...in order to not indirectly depend on `qt` bindings.
> Bump ert and libres

- apt_install.sh
Some `apt-install` commands are now obsolete after we can do `pip install opm`.
> Remove unnecessary apt-get installs

- src/flownet/ahm/_ahm_iteration_analytics.py
Partially addresses #61.
A new way of loading data from the reference simulation (OPM-Flow/Eclipse) is added, using functionality from `flownet.data.from_eclipse` instead of the previous approach of fetching data from the observation file into dictionary which was causing the random order behavior
> Fixes bug in analysis workflow

- src/flownet/config_parser/_config_parser.py
- src/flownet/network_model/_generate_connections.py
> Fixed bug where the config would be parsed incorrectly when no aquifer is defined

- build_environment.sh
Might be related to #114. Bump `ert` and `libres` to latest released versions, and see if problem with hanging realizations in `ert` disappears.
> Bump ert and libres dependencies

- setup.py
- src/flownet/network_model/_network_model.py
- src/flownet/utils/raytracing.py
Close #102 
The ray tracing is now performed:
1) Loop through all faults
2) Perform a triangulation of all points belonging to a fault plane and store the triangles
3) For each connection, find all triangles in its bounding box, perform ray tracing using the Möller-Trumbore intersection algorithm.
4) If an intersection is found, identify the grid blocks that are associated with the intersection.
The process has now been reduced in time from multiple minutes to seconds (depending on the config settings).
> Speed up ray tracing

- src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
Closes #140 
NB. Target is currently set to `1* = RATE`; we could consider exposing this setting to the user, like:
```yaml
flownet:
schedule:
injection_target: BHP
```
> Fix WCONINJH template

- .github/CODEOWNERS
- .github/workflows/flownet.yml
Add GitHub `CODEOWNER`, and also (since we are in a rapid development phase) deploy documentation to GitHub pages on merges to `master` (instead of only on releases).
---
> Add CODEOWNERS and deploy docs on merge to master

- src/flownet/_command_line.py
Running `flownet` without arguments no returns the help instead of an empty `Namespace()` error.
---
> Return CLI help if no arguments supplied to flownet

- .github/workflows/flownet.yml
- CHANGELOG.md
- src/flownet/_command_line.py
- src/flownet/config_parser/_config_parser.py
- src/flownet/config_parser/_config_parser_pred.py
- src/flownet/config_parser/_merge_configs.py
- tests/test_merge_configs.py
User can now have a _base_ configuration file, and also provide an optional configuration file which will be merged into the base configuration.
---
> Recursive merge configs

- .github/workflows/flownet.yml
- CHANGELOG.md
- src/flownet/ahm/_run_ahm.py
- src/flownet/config_parser/_config_parser.py
PR #160 closed using EQLNUM regions from source model, this PR deals with using source model SATNUM regions.
For models where many flow tubes end up outside of the source model simulation grid, looping through all cells to find the closest region can be time consuming. Changed here to find the closest flow tube allready assigned a region, which is much faster (and close to the same).
---
> Use source model SATNUM regions when generating a FlowNet

- CHANGELOG.md
- src/flownet/ahm/_run_ahm.py
- src/flownet/config_parser/_config_parser.py
- src/flownet/realization/_schedule.py
- src/flownet/realization/_simulation_keywords.py
- src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
- src/flownet/templates/observations.ertobs.jinja2
Adding the possibility to change how the production wells are controlled in the WCONHIST keywords. This will not be controlled by one keyword in the config yaml.
---
> Adding possibility to change control modes in history matching

- src/flownet/ahm/_run_ahm.py
- src/flownet/config_parser/_config_parser.py
Currently the low model relative permeability curves for interpolation is created using all minimum values from relative permeability model parameters. This PR adds a boolean to the config file for all relative permeability model parameters, allowing for to define whether the low or high values should be used in generating the low/high relative permeability curves for interpolation
---
> Generating low/base/high SCAL recommendations for pyscal

- CHANGELOG.md
- src/flownet/config_parser/_config_parser_hyperparam.py
> Fix duplicate names in hyperopt parameters by using full yaml path

- src/flownet/ert/_run_subprocess.py
This fix makes sure that when ERT fails, for whatever reason, a `SubprocessError` is raised and mlflow registers the run as a failed run.
---
> Raise SubprocessError for non-zero returncode of the ERT subprocess

- setup.py
- src/flownet/ert/_run_subprocess.py
ERT sometimes hangs, see https://github.com/equinor/libres/issues/984.
This PR adds a timer which, after 15 minutes of complete silence from the ERT process, kills it including all child processes.
---
> Add timer to kill ERT if no output for 15 minutes

- setup.py
Pin `xrld<2` to avoid version conflicts with semeio
> Pin xrld to <2.0 to avoid version conflixt with semeio

- src/flownet/ahm/_run_ahm.py
PR #251 added distribution parameters. These additional parameters were not accounted for in the generation of a pandas dataframe for the interpolation parameters (always uniform on the interval -1 to 1). Hence, the code failed with an AssertionError when using relative permeability interpolation
---
> bug when interpolate relperm is true

- CHANGELOG.md
- src/flownet/ahm/_run_ahm.py
- src/flownet/config_parser/_config_parser.py
- src/flownet/data/from_flow.py
- src/flownet/network_model/_generate_connections.py
- tests/test_data_flow.py
- tests/test_generate_connections.py
> I276 enabled new layering functionality

- CHANGELOG.md
- src/flownet/ahm/_ahm_iteration_analytics.py
*Fixes bug where the analytics module would fail for iterations larger than 9 (i.e., iteration number with two or more digits)*
---
> Fixes bug where the analytics module would fail for iterations > 9

- CHANGELOG.md
- setup.py
- src/flownet/utils/observations.py
- src/flownet/utils/plot_results.py
- tests/test_check_obsfiles_ert_yaml.py
This PR adds a simple plotting tool which allows you to plot the results of FlowNet runs.
---
> Add simple plotting tool

- CHANGELOG.md
- src/flownet/utils/plot_results.py
This PR is a bugfix for a memory leak in the result plotting script.
---
> Fix memory leak in result plotting script

- src/flownet/config_parser/_config_parser.py
- src/flownet/network_model/_generate_connections.py
- src/flownet/network_model/_mitchell.py
- tests/test_generate_connections.py
- tests/test_mitchell.py
> Node placement in volume of original model

- CHANGELOG.md
- src/flownet/config_parser/_config_parser.py
- src/flownet/parameters/_relative_permeability.py
If you want to create a wide range for both SWL and SWCR there is a large chance for generating non-physical values, where SWCR is lower than SWL. This PR adds a parameter to the config yaml (defaulted to false), that provides the opportunity to calculate the SWCR from the SWL by adding a delta value. 
If `swcr_add_to_swcr` is set to `True` the `swcr` parameter in the config yaml will be treated as a prior distribution for the delta value that will be added to SWL, not as a prior distribution for SWCR directly.
---
> Add delta to SWL to calculate SWCR

- CHANGELOG.md
- src/flownet/templates/observations.ertobs.jinja2
- src/flownet/templates/observations.yamlobs.jinja2
The yamlobs jinja template has some bugs in it for writing observations of injection
---
> Fix observation templates

- CHANGELOG.md
- src/flownet/ahm/_run_ahm.py
- src/flownet/config_parser/_config_parser.py
When setting the scheme to regions_from_sim the EQLNUM regions in the input simulation model were used to generate the EQLNUM regions for the FlowNet model. This PR makes this more flexible by allowing any region parameter from the INIT file to be used.
---
> Make EQLNUM regions in FlowNet based on region parameter from simulation model

- src/flownet/config_parser/_config_parser.py
Solve deprecation warning: remove .Required in config parser
The Required option is going to be deprecated @olwijn, no need to specify this anymore. It will still work, but it leads to deprecation warnings when running FlowNet.
---
> Solve deprecation warning: remove .Required in config parser

- CHANGELOG.md
- src/flownet/parameters/_equilibration.py
- src/flownet/templates/THPRES.jinja2
There is currently a bug in the code that prints threshold pressures between all flow tubes if there is more than one equilibrium region. Thus many threshold pressures are added within one equilibrium region as well (probably from when individual and global were the only available options). This PR makes it such that THPRES is only printed for neighboring equilibrium regions (sorted for readability).
---
> Only print THPRES between neighboring equil regions

- src/flownet/config_parser/_config_parser.py
With this PR, in case for an observation either rel_error or min_error is missing an error message is given:
e.g:
data_source:
simulation:
input_case: ../input_model/egg/EGG_MODEL_ECL
vectors:
WBHP:
rel_error: 0.005
WOPR:
min_error: 1
gives the error:
_ValueError: Both min_error and rel_error must be set. This requirement is not satisfied for  ['WBHP', 'WOPR']  observations_
In case both rel_error and min_error are absent flownet gives an error as the configuration file  does not satisfy the template requirements as defined  in _config_parser.py  (using the **configsuite** module). The error message is however not very insightful:
_ValueError: The configuration is not valid:Is x a dictionary is false on input 'None'._ 
To fix this would require to dig into the  **configsuite** module …
> Rel error 409

- CHANGELOG.md
- src/flownet/config_parser/_config_parser.py
- src/flownet/data/from_flow.py
- src/flownet/realization/_schedule.py
- src/flownet/realization/_simulation_keywords.py
- src/flownet/static/SUMMARY.inc
- src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
- src/flownet/templates/TEMPLATE_MODEL.DATA.jinja2
- src/flownet/templates/observations.ertobs.jinja2
- src/flownet/templates/observations.yamlobs.jinja2
- tests/test_check_obsfiles_ert_yaml.py
This PR continues PR #410 (add brine support)
This PR  adds on top of P#410  the creation of WSALT entries in the HISTORY_SCHEDULE.inc
The  flownet-testcases/ norne_salt  (PR #50 of flownet-testcases repo) is used as testcase
---
- [ x] : This PR closes #381.
- [ x]  I have broken down my PR into the following tasks:
- [ x] : I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- flownet-testcases/ norne_salt
> Add brine p

- CHANGELOG.md
- src/flownet/realization/_schedule.py
*Prevents unnecessary repeated search for well starting date inside for-loop when processing historical schedule production data*
---
> Prevents unnecessary repeated search for well starting date

- src/flownet/config_parser/_config_parser.py
- src/flownet/data/from_flow.py
- src/flownet/ert/forward_models/_flow_job.py
- src/flownet/realization/_schedule.py
- src/flownet/realization/_simulation_keywords.py
- src/flownet/static/SUMMARY.inc
- src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2
- src/flownet/templates/TEMPLATE_MODEL.DATA.jinja2
- src/flownet/templates/observations.ertobs.jinja2
- src/flownet/templates/observations.yamlobs.jinja2
- tests/test_check_obsfiles_ert_yaml.py
The purpose of this PR is to allow for history matching production fluid temperatures. Main adjustement:
1) keyword `WTPCHEA` (temperature of producers) added for parsing  (`_config_parser.py`)
2) extended `phases` with additional element `temp`. Also `brine` is allowed now to be specified under `phases` item in the yml config file. Thus the items `'oil', 'gas', 'water', 'disgas', 'vapoil', 'brine' and 'temp'` can all be specified now under the `phases` keyword. (Note the term `phases ` is not so appropriate anymore and should may be renamed) (`_config_parser.py`)
3) added `WTPCHEA` and `WTICHEA` to dataframe (`from_flow.py`)
4) helper function adedd to create `WTEMP` for injection temperature specification. The `has_brine` method commented out as `brine` keyword should now be specified …
> adaptations to allow for production temperature history matching
