examples/norne_parameters.yml

Fixed logunif-error in norne_parameters.yml

---

.github/workflows/flownet.yml

Deploy GitHub pages on merge to master

---

.github/workflows/flownet.yml

...and add important emojis to CI dashboard.

Run scheduled CI

---

src/flownet/ahm/_ahm_iteration_analytics.py
tests/test_calculation_accuracy_metric.py
tests/test_normalize_data.py
tests/test_prepare_flownet_data.py
tests/test_prepare_opm_reference_data.py

Adds more tests for iteration analytics workflow functions

---

src/flownet/data/from_eclipse.py

Closes #36 . The time shift should make sure that the data enter the schedule as well targets at the correct time. Note that this also moves the observations in time. These should therefore no longer be extracted from the schedule.

Remove interpolation of ECLIPSE data and apply time shift

---

build_environment.sh

Currently only available from test-PyPI, but soon avilable from official PyPI. 🔪 away ~6 minutes of build time... 🏎️

Get opm-common from PyPI

---

src/flownet/data/from_eclipse.py

Use report_steps only from UNSMRY input

---

build_environment.sh
setup.py

Use official PyPI for opm-common

---

src/flownet/ahm/_assisted_history_matching.py

Grab and print ERT error message if ERT fails

---

src/flownet/config_parser/_config_parser.py
src/flownet/config_parser/_config_parser_pred.py

Convert to absolute paths if neccessary

---

examples/flow_model_import.py
examples/norne_parameters.yml
src/flownet/ahm/_run_ahm.py
src/flownet/config_parser/_config_parser.py
src/flownet/data/__init__.py
src/flownet/data/from_flow.py
src/flownet/network_model/_create_egrid.py
src/flownet/network_model/_generate_connections.py
src/flownet/network_model/_one_dimensional_model.py
src/flownet/parameters/_equilibration.py
src/flownet/parameters/_relative_permeability.py
src/flownet/realization/_render_realization.py
src/flownet/realization/_schedule.py
src/flownet/realization/_simulation_realization.py
src/flownet/utils/write_grdecl_file.py
tests/configs/norne_parameters.yml
tests/test_flow_import.py

Rename Eclipse to Flow

---

setup.py
src/flownet/config_parser/_config_parser.py
src/flownet/config_parser/_config_parser_pred.py

Closes #87 (following instructions in https://configsuite.readthedocs.io/en/stable/user_guide/deprecated_behaviour.html).

Support new and future versions of configsuite

---

src/flownet/config_parser/_config_parser.py

Add AllowNone for relative permeability and training_set_end_date

---

.github/workflows/flownet.yml
src/flownet/ahm/_run_ahm.py
src/flownet/config_parser/_config_parser.py

Rock and Aquifer allowed as optional keyword in config

---

src/flownet/ahm/_run_ahm.py

Fixed bug where faults would be inserted as an uncertain parameter, when no faults were present

---

src/flownet/ahm/_run_ahm.py

Fixed relperm parameter bug

---

src/flownet/ahm/_assisted_history_matching.py

This is basically a workaround for https://github.com/equinor/libres/issues/984.

Overall timeout on ert run

---

src/flownet/config_parser/_config_parser.py

AllowNone for queue name

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md

This PR adds a change log as well as a PR template.
---

Add PR template and CHANGELOG.md

---

.github/workflows/flownet.yml

Followup of https://github.com/equinor/flownet-testdata/pull/11.

Add Brugge to FlowNet CI

---

.github/workflows/flownet.yml

This PR removes the github workflow cache, which has shown not to be very stable in our setup.
---

Remove cache from Github workflow

---

docs/conf.py
docs/configuration_file.rst
src/flownet/config_parser/_config_parser.py

Waiting on feedback on https://github.com/equinor/configsuite/pull/157.

Automatically create documentation from schema

---

README.md

Remove conda from install instructions

---

docs/conf.py
docs/configuration_file.rst
src/flownet/config_parser/_config_parser.py
src/flownet/network_model/_network_model.py

Adding midpoint getter to network model class.

Midpoint network property

---

src/flownet/realization/_schedule.py
src/flownet/realization/_simulation_keywords.py

Speed up Schedule creation
Time spent on `get_well_start_date` in Norne case:
- before changes: **58.64 s**
- After changes:  **2.3 s**
---

Speed up schedule creation

---

.github/workflows/flownet.yml

Add PYTHONWARNINGS to CI

---

src/flownet/ert/_create_ert_setup.py

Fix crashing CI

---

.github/workflows/flownet.yml
src/flownet/ahm/_run_ahm.py

Add Python 3.8 to github workflows.
---

Add python 3.8 to github workflow

---

docs/introduction.rst

Update link to Brugge dataset
---

Update link to Brugge dataset in docs

---

src/flownet/static/SUMMARY.inc

Refactor the `SUMMARY.inc` static file and add requested vectors.
---

Refactor SUMMARY.inc and add vectors

---

src/flownet/ahm/_ahm_iteration_analytics.py
tests/test_normalize_data.py

Fixes analysis workflow for flat BHP in Egg model

---

docs/introduction.rst

---
- [v] :tada: This PR closes #229 .
- [v] :scroll: I have broken down my PR into the following tasks:
- [v] Add a reference to the publication to the Introduction of the documentation
- [v] :books: I have considered updating the documentation.

added reference to documentation

---

src/flownet/hyperparameter/_run_hyper.py

Report parameters early in mflow + print exceptions in hyperopt runs

---

src/flownet/realization/_schedule.py

*Add support for empty schedule.*
---

Add posibility to create empty schedule 

---

src/flownet/ert/_flow_job.py

Check $FLOW_PATH in environment variables and check `which flow`

---

src/flownet/parameters/_aquifer.py
src/flownet/parameters/_equilibration.py
src/flownet/parameters/_fault_transmissibility.py
src/flownet/parameters/_porv_poro_trans.py
src/flownet/parameters/_relative_permeability.py

Docstring changes

---

src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2

corrects a time shift in the FlowNet schedule relative to data

---

src/flownet/parameters/_relative_permeability.py

This PR addresses some minor issues in the i278 PR from @olelod such that we can merge it now.

Fixes to PR for i278

---

CHANGELOG.md

Update changelog for 0.5.0 release

Update changelog for 0.5.0 release

---

CHANGELOG.md
src/flownet/config_parser/_config_parser.py
src/flownet/network_model/_generate_connections.py

i343_Allow a single number to be entered for the number of additional flow nodes

---

CHANGELOG.md
src/flownet/ahm/_assisted_history_matching.py
src/flownet/config_parser/_config_parser.py
src/flownet/config_parser/_config_parser_pred.py
src/flownet/ert/_run_subprocess.py
src/flownet/prediction/_run_pred.py

Expose FlowNet timeout to user and increase default timeout

---

src/flownet/config_parser/_config_parser.py
src/flownet/config_parser/_config_parser_pred.py
src/flownet/ert/forward_models/_iteration_analytics.py
src/flownet/parameters/probability_distributions.py

This PR fixes LGTM warnings.
---

Fix LGTM warnings

---

src/flownet/ahm/_run_ahm.py
src/flownet/parameters/_relative_permeability.py

A new fix due to complaints from the latest mypy version
---

fix for failing CI

---

.pylintrc

increase max attributes pylint

---

.pylintrc
src/flownet/ahm/_run_ahm.py
src/flownet/config_parser/_config_parser.py
src/flownet/ert/_create_ert_setup.py
src/flownet/network_model/_mitchell.py
tests/test_relative_permeability.py

fixes due to new version of pylint

---

README.md

Forgot this in previous PR....
This adds 3.9 to the badge on the readme page.
---

Add 3.9 to shields on README

---

src/flownet/config_parser/_config_parser.py
src/flownet/ert/_run_subprocess.py
src/flownet/ert/forward_models/_flow_job.py
src/flownet/ert/forward_models/_save_iteration_parameters.py
src/flownet/parameters/_relative_permeability.py
src/flownet/utils/write_grdecl_file.py

Update code corresponding to warnings in new pylint version

---

CHANGELOG.md

release 0.5.3
